[tools]
node = "lts"
pnpm = "latest"
python = "3.12"
ruby = "4.0.1"
terraform = "1.14.4"
go = "latest"
deno = "latest"
gh = "latest"
ghq = "latest"
fzf = "latest"
jq = "latest"
eza = "latest"
ripgrep = "latest"
delta = "latest"
bat = "latest"
fd = "latest"
lazygit = "latest"
yazi = "latest"
uv = "latest"
